services:
  task-cli:
    build:
      context: .
      dockerfile: apps/task-cli/Dockerfile
    volumes:
      # Persist the tasks.json file to the host
      - ./apps/task-cli/tasks.json:/app/tasks.json
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: [ "dotnet", "TaskTracker.dll" ]
